services:
  #django app
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - django_redis
    env_file:
      - ./core/.env

  #Redis
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - "6379:6379"
  
  #database
  django_db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: django_db_dev
      POSTGRES_USER: django_dev
      POSTGRES_PASSWORD: postgres_dev
    ports:
      - "5433:5432"
    volumes:
      - .dbdata:/var/lib/postgresql